version: '3.5'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  bot:
    build:
      context: app
      dockerfile: Dockerfile
    image: result/latest
    environment:
      TOKEN: "6256751542:AAFFCrPc6-5HVIhTPekb4LYH10qtgzPp3sY"
      WEBHOOK: "https://TODO.ngrok.io"
      DBNAME: locky_data
      HOST: localhost
      PORT: 5432
      USER: postgres
      PASSWORD: postgres
      SSLMODE: disable